Already logged in!
CRAWLING
INSERTING
Traceback (most recent call last):
  File "Backend/synchronize.py", line 261, in <module>
    insert()
  File "Backend/synchronize.py", line 228, in insert
    for n in range(3, driver.get_elements_size(xpath["messages_count"])+1):
  File "/Users/daniel/Documents/Master/ChatBot Projekt/convrt/Backend/classes/core.py", line 138, in get_elements_size
    elements = self.get_elements(xpath)
  File "/Users/daniel/Documents/Master/ChatBot Projekt/convrt/Backend/classes/core.py", line 108, in get_elements
    elements = self.find_elements_by_xpath(xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 410, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1005, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed
  (Session info: chrome=88.0.4324.150)

